Class Megamix_MelPlayer : DoomPlayer
{
	Default
	{
		Player.ViewHeight 47;
		Player.AttackZOffset 20;
		Player.JumpZ 9.0;
		Player.StartItem "MeleeButtonActor", 1;
		Player.StartItem "IsMel", 1;	
		Player.StartItem "Weapon_Mel_Melee";
		Player.SoundClass "Mel";
		Player.DisplayName "Crosswell";
		//Player.Face "MC1";
		Player.Portrait "MELCPORT";
		Player.WeaponSlot 1, "Weapon_Mel_Melee";
		Species "Player";
		+THRUSPECIES
		+PLAYERPAWN.NOTHRUSTWHENINVUL
	}
}